asset_path: /home_nfs/yi-ray/miniconda3/envs/phys-vidsim/lib/python3.12/site-packages/robosuite/models/assets/objects/meshes/milk.obj
usd_dir: /project/yi-ray/IsaacLab/_robosuite_usd/milk
usd_file_name: milk.usd
force_usd_conversion: true
make_instanceable: true
mass_props:
  mass: 0.5
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: false
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: 5.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: null
  contact_offset: 0.005
  rest_offset: 0.0
  torsional_patch_radius: null
  min_torsional_patch_radius: null
mesh_collision_props:
  usd_func: pxr.UsdPhysics:MeshCollisionAPI
  physx_func: pxr.PhysxSchema:PhysxConvexDecompositionCollisionAPI
  mesh_approximation_name: convexDecomposition
  hull_vertex_limit: null
  max_convex_hulls: null
  min_thickness: null
  voxel_resolution: null
  error_percentage: null
  shrink_wrap: true
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2026-07-23 at 06:55:21.
##
